name = "cf-ai-planpal"
main = "src/worker.ts"
compatibility_date = "2025-11-14"
compatibility_flags = ["nodejs_compat"]

[env.development]
vars = { ENVIRONMENT = "development", MODEL = "@cf/meta/llama-3.1-8b-instruct" }

[ai]
binding = "AI"
remote = true

[[durable_objects.bindings]]
name = "PLANPAL_DO"
class_name = "PlanPalDO"

[[migrations]]
tag = "v1"
new_classes = ["PlanPalDO"]

[[migrations]]
tag = "v2"
renamed_classes = [
	{ from = "Chat", to = "PlanPalDO" }
]
